const dummyData = {
    categories: [
        "Shirt",
        "Pant",
        "Shoes",
        "Watch",
    ],
    brands: [
        "Adidas",
        "Ipanema",
        "Jordan",
        "Boss"
    ],
    colors: [
        "Black",
        "Red",
        "Blue",
        "Grey"
    ],
    products: [
        {
            "id": 1,
            "name": "Shirt 1",
            "category": "Shirt",
            "brand": "Adidas",
            "color": "Black",
            "url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRiaJz-J2xB8WW4AP1JKw1x0abgHBCPESTTMvclJZyYPg&s",
        },
        {
            "id": 2,
            "name": "Shirt 2",
            "category": "Shirt",
            "brand": "Adidas",
            "color": "Blue",
            "url": "https://thumblr.uniid.it/product/211277/aaebee9dc574.jpg",
        },
        {
            "id": 3,
            "name": "Shirt 3",
            "category": "Shirt",
            "brand": "Ipenema",
            "color": "Grey",
            "url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTWKfkU-CWjxZ81csPE24oHlIzRBCMgauZg39nRwd9JWt7QJFoGp8kghENnGBa1K6EsbIc&usqp=CAU",
        },
        {
            "id": 4,
            "name": "Shirt 4",
            "category": "Shirt",
            "brand": "Ipenema",
            "brand": "Red",
            "url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSvNtaGDR3yt0XpUWY7095HRE5ERvsfFWPHJQ&usqp=CAU",
        },
        {
            "id": 5,
            "name": "Shirt 5",
            "category": "Shirt",
            "brand": "Boss",
            "color": "Black",
            "url": "https://1202139849.rsc.cdn77.org/temp/1685350802_b0abf078998de4f824ed1a73d9bcaa6d.jpg",
        },
        {
            "id": 6,
            "name": "Pant 1",
            "category": "Pant",
            "brand": "Adidas",
            "color": "Blue",
            "url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbsQETBFzAaBM8fdy8IhLsKzdaNMlB5ScCNA&usqp=CAU",
        },
        {
            "id": 7,
            "name": "Pant 2",
            "category": "Pant",
            "brand": "Adidas",
            "color": "Grey",
            "url": "https://assets.adidas.com/images/w_600,f_auto,q_auto/a2cce532dad0490a9a5cac3800e5620e_9366/Tiro_21_Track_Pants_Grey_GJ9868_21_model.jpg",
        },
        {
            "id": 8,
            "name": "Pant 3",
            "category": "Pant",
            "brand": "Ipenema",
            "color": "Red",
            "url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTTqtKRyytf8BgrRusP7J48-jaULXB90XOliA&usqp=CAU",
        },
        {
            "id": 9,
            "name": "Pant 4",
            "category": "Pant",
            "brand": "Jordan",
            "color": "Black",
            "url": "https://sa.kickscrew.com/cdn/shop/products/main-square_eda83cf7-aff2-4e40-802e-6159f9cdfc0a_523x.jpg?v=1694785888",
        },
        {
            "id": 10,
            "name": "Pant 5",
            "category": "Pant",
            "brand": "Boss",
            "color": "Blue",
            "url": "https://static.privatesportshop.com/img/p/3804135-11457904-thickbox.jpg",
        },
        {
            "id": 11,
            "name": "Shoe 1",
            "category": "Shoe",
            "brand": "Adidas",
            "color": "Grey",
            "url": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/8244a99f0c5643bbb40c26b7a571e8b5_9366/Grand_Court_Alpha_Cloudfoam_Lifestyle_Court_Comfort_Shoes_Grey_ID5288_01_standard.jpg",
        },
        {
            "id": 12,
            "name": "Shoe 2",
            "category": "Shoe",
            "brand": "Adidas",
            "color": "Red",
            "url": "https://assets.adidas.com/images/w_600,f_auto,q_auto/82af75292ef44ea4980baf80017ceb80_9366/Tyshawn_Remastered_Shoes_Red_IG5278_01_standard.jpg",
        },
        {
            "id": 13,
            "name": "Shoe 3",
            "category": "Shoe",
            "brand": "Ipenema",
            "color": "Black",
            "url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR43PkkPhFKzAOzqJsSCsqdOk91e2k5tMBDUA&usqp=CAU",
        },
        {
            "id": 14,
            "name": "Shoe 4",
            "category": "Shoe",
            "brand": "Jordan",
            "color": "Blue",
            "url": "https://static.nike.com/a/images/t_prod_ss/w_960,c_limit,f_auto/eaa42dac-16bb-4174-accd-2bbd06cee899/air-jordan-1-university-blue-release-date.jpg",
        },
        {
            "id": 15,
            "name": "Shoe 5",
            "category": "Shoe",
            "brand": "Boss",
            "color": "Grey",
            "url": "https://photos6.spartoo.eu/photos/240/24042801/24042801_500_A.jpg",
        },
        {
            "id": 16,
            "name": "Watch 1",
            "category": "Watch",
            "brand": "Adidas",
            "color": "Red",
            "url": "https://f.nooncdn.com/p/pzsku/ZE1F7193B49330F4829A3Z/45/_/1691789825/1d212b71-4f69-4733-b69f-568dd398e527.jpg?format=jpg&width=310",
        },
        {
            "id": 17,
            "name": "Watch 2",
            "category": "Watch",
            "brand": "Adidas",
            "color": "Black",
            "url": "https://4.imimg.com/data4/WK/IJ/ANDROID-25215069/product.jpeg",
        },
        {
            "id": 18,
            "name": "Watch 3",
            "category": "Watch",
            "brand": "Ipenema",
            "color": "Blue",
            "url": "https://m.media-amazon.com/images/I/51aYz5m+4lL._AC_SY780_.jpg",
        },
        {
            "id": 19,
            "name": "Watch 4",
            "category": "Watch",
            "brand": "Jordan",
            "color": "Grey",
            "url": "https://abingdonco.com/cdn/shop/files/2000x2000AbingdonJordanBlackSteelAnalogQuartzTachymeterAutomotiveWatch-1Front_1800x.jpg?v=1699711824",
        },
        {
            "id": 20,
            "name": "Watch 5",
            "category": "Watch",
            "brand": "Boss",
            "color": "red",
            "url": "https://www.mastersintime.com/pictures/hugo-boss-view-1513988-14160780.jpg",
        },
    ],
};
